name: Jekyll site CI

on:
  pull_request:
    paths-ignore:
      - "**/CITATION.cff"
  push:
    paths-ignore:
      - "**/CITATION.cff"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll build --future
